# --------
# using scipy, it's kinda big but that should not be a problem
# base-notebook lacks at least numpy, widgets, so...
#FROM nbhosting/scipy-notebook:latest


# --------
# install plotly for w7
#RUN pip install plotly


# --------
# install scikit-image
#RUN pip install scikit-image

# --------
# install geopy
#RUN pip install geopy